GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4OTY1NzgwLCJleHAiOjE2NDg5NjU3OTV9.TB-hOTxyc_DSiPKdQkEfP6UB9aebIRRnQteN4BuLv1Q

###

GET http://localhost:4000/tokens

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4OTY1NzI0fQ.7zUF1sZqmNLYclMAimYy0h7gDPcL9l4t-3MVuHTlYM8"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4OTY1NzI0fQ.7zUF1sZqmNLYclMAimYy0h7gDPcL9l4t-3MVuHTlYM8"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}